version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: myproject_nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./volumes/static:/app/static
    depends_on:
      - web
    links:
      - web
  web:
    build: .
    container_name: myproject_webapp
    entrypoint: /app/docker-entrypoint.sh
    volumes:
      - ./volumes/logs:/app/logs
      - ./volumes/static:/app/static
    env_file:
      - config/.env
    environment:
      - DEPLOY=docker
    depends_on:
      - db
    links:
      - db
    expose:
      - "8000"
  db:
    image: postgres:latest
    container_name: myproject_postgres
    restart: always
    env_file:
      - config/.env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/

# networks:
#     default:
#         external:
#             name: myproject-network